# fly.toml app configuration file generated for bin-monitor-api on 2023-06-11T13:30:43-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bin-monitor-api"
primary_region = "gru"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
